import { useState } from "react";
import {
  BarChart, Bar, PieChart, Pie, Cell, LineChart, Line,
  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
} from "recharts";
import { mockRapports, mockFiliales } from "../data/mockData";
import { useAppSettings } from "../contexts/AppSettingsContext";

// ─── TRADUCTIONS 
const T = {
  fr: {
    title: "Rapports", subtitle: "Génération et consultation des rapports",
    newBtn: "Générer un rapport",
    kpi1: "Total rapports", kpi2: "Générés", kpi3: "En attente / En cours",
    chartBar: "Rapports générés par mois", chartPie: "Répartition par type",
    chartLine: "Taux de disponibilité (6 mois)",
    searchPlaceholder: "Rechercher un rapport...",
    tableCols: ["Rapport", "Type", "Date", "Filiale", "Incidents", "Dispo", "Statut", "Actions"],
    par: "Par", see: "Voir", pdf: "PDF", filterAll: "Tous", export: "Exporter",
    generatingPdf: "PDF...",
    statuts: { Généré: "Généré", "En attente": "En attente", "En cours": "En cours" },
    modalType: "Type", modalDate: "Date", modalFiliale: "Filiale",
    modalAgence: "Agence", modalIncidents: "Incidents",
    modalDispo: "Disponibilité", modalStatut: "Statut", modalTaille: "Taille",
    // Modal générer
    genTitle: "Générer un rapport",
    genType: "Type de rapport *", genTypeDefault: "— Sélectionner un type",
    genPeriodeDebut: "Date de début *", genPeriodeFin: "Date de fin *",
    genFiliale: "Filiale", genFilialeDefault: "Toutes les filiales",
    genAgence: "Agence", genAgenceDefault: "Toutes les agences",
    genFormat: "Format d'export",
    genCancel: "Annuler", genSubmit: "Générer",
    genGenerating: "Génération en cours...",
    TYPES_RAPPORT: ["Mensuel", "Hebdomadaire", "Trimestriel", "Annuel", "Incident"],
    FORMATS: ["PDF", "Excel", "CSV"],
    // PDF
    pdfConf: "CONFIDENTIEL", pdfFooter: "GFALens — Rapport automatique",
    pdfSummary: "Résumé", pdfDetails: "Détails",
    pdfGeneratedBy: "Généré par", pdfDate: "Date",
    pdfFiliale: "Filiale", pdfAgence: "Agence",
    pdfIncidents: "Incidents", pdfDispo: "Disponibilité",
    pdfStatut: "Statut", pdfSize: "Taille",
  },
  en: {
    title: "Reports", subtitle: "Report generation and consultation",
    newBtn: "+ Generate report",
    kpi1: "Total reports", kpi2: "Generated", kpi3: "Pending / In progress",
    chartBar: "Reports generated per month", chartPie: "Distribution by type",
    chartLine: "Availability rate (6 months)",
    searchPlaceholder: "Search a report...",
    tableCols: ["Report", "Type", "Date", "Branch", "Incidents", "Avail.", "Status", "Actions"],
    par: "By", see: "View", pdf: "PDF", filterAll: "All", export: "Export",
    generatingPdf: "PDF...",
    statuts: { Généré: "Generated", "En attente": "Pending", "En cours": "In Progress" },
    modalType: "Type", modalDate: "Date", modalFiliale: "Branch",
    modalAgence: "Agency", modalIncidents: "Incidents",
    modalDispo: "Availability", modalStatut: "Status", modalTaille: "Size",
    genTitle: "Generate a report",
    genType: "Report type *", genTypeDefault: "— Select a type",
    genPeriodeDebut: "Start date *", genPeriodeFin: "End date *",
    genFiliale: "Branch", genFilialeDefault: "All branches",
    genAgence: "Agency", genAgenceDefault: "All agencies",
    genFormat: "Export format",
    genCancel: "Cancel", genSubmit: "Generate",
    genGenerating: "Generating...",
    TYPES_RAPPORT: ["Monthly", "Weekly", "Quarterly", "Annual", "Incident"],
    FORMATS: ["PDF", "Excel", "CSV"],
    pdfConf: "CONFIDENTIAL", pdfFooter: "GFALens — Automated Report",
    pdfSummary: "Summary", pdfDetails: "Details",
    pdfGeneratedBy: "Generated by", pdfDate: "Date",
    pdfFiliale: "Branch", pdfAgence: "Agency",
    pdfIncidents: "Incidents", pdfDispo: "Availability",
    pdfStatut: "Status", pdfSize: "Size",
  },
  mg: {
    title: "Tatitra", subtitle: "Famoronana sy fitazomana tatitra",
    newBtn: "+ Mamorona tatitra",
    kpi1: "Tatitra rehetra", kpi2: "Novolavolaina", kpi3: "Miandry / Eo am-pandehanana",
    chartBar: "Tatitra novolavolaina isam-bolana", chartPie: "Fizarana araka ny karazana",
    chartLine: "Tahan'ny fahafahana (6 volana)",
    searchPlaceholder: "Hikaroka tatitra...",
    tableCols: ["Tatitra", "Karazana", "Daty", "Filiale", "Olana", "Fahafahana", "Toe-javatra", "Hetsika"],
    par: "Nataon'i", see: "Hijery", pdf: "PDF", filterAll: "Rehetra", export: "Anatontany",
    generatingPdf: "PDF...",
    statuts: { Généré: "Vita", "En attente": "Miandry", "En cours": "Eo am-pandehanana" },
    modalType: "Karazana", modalDate: "Daty", modalFiliale: "Filiale",
    modalAgence: "Agence", modalIncidents: "Olana",
    modalDispo: "Fahafahana", modalStatut: "Toe-javatra", modalTaille: "Haben'ny rakitra",
    genTitle: "Mamorona tatitra",
    genType: "Karazana tatitra *", genTypeDefault: "— Misafidy karazana",
    genPeriodeDebut: "Daty fiandohana *", genPeriodeFin: "Daty famaranana *",
    genFiliale: "Filiale", genFilialeDefault: "Filiale rehetra",
    genAgence: "Agence", genAgenceDefault: "Agence rehetra",
    genFormat: "Endrika export",
    genCancel: "Hanafoana", genSubmit: "Mamorona",
    genGenerating: "Eo am-famoronana...",
    TYPES_RAPPORT: ["Isam-bolana", "Isam-herinandro", "Telo volana", "Taona", "Olana"],
    FORMATS: ["PDF", "Excel", "CSV"],
    pdfConf: "MIAFINA", pdfFooter: "GFALens — Tatitra otomatika",
    pdfSummary: "Fintinana", pdfDetails: "Antsipiriany",
    pdfGeneratedBy: "Nataon'i", pdfDate: "Daty",
    pdfFiliale: "Filiale", pdfAgence: "Agence",
    pdfIncidents: "Olana", pdfDispo: "Fahafahana",
    pdfStatut: "Toe-javatra", pdfSize: "Haben'ny rakitra",
  },
};

// Filtre tableau — sans Audit
const TYPES_FILTRE = ["Tous", "Mensuel", "Hebdomadaire", "Trimestriel", "Annuel", "Incident"];

const STATUT_STYLES = {
  Généré:       "bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-300",
  "En attente": "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/40 dark:text-yellow-300",
  "En cours":   "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300",
};

const barData = [
  { mois: "Oct", mensuel: 4, hebdo: 12, incidents: 2 },
  { mois: "Nov", mensuel: 4, hebdo: 13, incidents: 1 },
  { mois: "Déc", mensuel: 4, hebdo: 14, incidents: 5 },
  { mois: "Jan", mensuel: 4, hebdo: 13, incidents: 3 },
  { mois: "Fév", mensuel: 4, hebdo: 11, incidents: 2 },
  { mois: "Mar", mensuel: 5, hebdo: 14, incidents: 1 },
];
const pieData = [
  { name: "Mensuel",      value: 35, color: "#1e3a8a" },
  { name: "Hebdomadaire", value: 40, color: "#3b82f6" },
  { name: "Trimestriel",  value: 10, color: "#60a5fa" },
  { name: "Incident",     value: 8,  color: "#ef4444" },
  { name: "Annuel",       value: 7,  color: "#8b5cf6" },
];
const lineData = [
  { mois: "Oct", dispo: 96.2 }, { mois: "Nov", dispo: 97.8 },
  { mois: "Déc", dispo: 95.1 }, { mois: "Jan", dispo: 98.3 },
  { mois: "Fév", dispo: 97.9 }, { mois: "Mar", dispo: 98.2 },
];
const tooltipStyle = {
  fontSize: 12, borderRadius: 8,
  backgroundColor: "#1f2937", border: "1px solid #374151", color: "#f9fafb",
};

// ─── EXPORTS ──────────────────────────────────────────────────
function exportExcel(rapport) {
  const rows = [
    ["Champ", "Valeur"],
    ["Titre", rapport.titre], ["Type", rapport.type],
    ["Date", rapport.dateGeneration], ["Filiale", rapport.filiale],
    ["Agence", rapport.agence], ["Incidents", rapport.incidents],
    ["Disponibilité", rapport.disponibilite], ["Statut", rapport.statut],
    ["Généré par", rapport.generePar], ["Taille", rapport.taille],
  ];
  const csv = rows.map(r => r.map(c => `"${c}"`).join(",")).join("\n");
  const blob = new Blob(["\uFEFF" + csv], { type: "application/vnd.ms-excel;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = `${rapport.titre.replace(/\s+/g, "_")}.xls`; a.click();
  URL.revokeObjectURL(url);
}

function exportCSV(rapport) {
  const rows = [
    ["Titre", "Type", "Date", "Filiale", "Agence", "Incidents", "Disponibilité", "Statut", "Généré par"],
    [rapport.titre, rapport.type, rapport.dateGeneration, rapport.filiale,
     rapport.agence, rapport.incidents, rapport.disponibilite, rapport.statut, rapport.generePar],
  ];
  const csv = rows.map(r => r.map(c => `"${c}"`).join(",")).join("\n");
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = `${rapport.titre.replace(/\s+/g, "_")}.csv`; a.click();
  URL.revokeObjectURL(url);
}

async function generatePDF(rapport, t) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210, M = 18, CW = 174;

  doc.setFillColor(30, 58, 138); doc.rect(0, 0, W, 48, "F");
  doc.setFillColor(59, 130, 246); doc.rect(0, 45, W, 3, "F");
  doc.setTextColor(255,255,255); doc.setFontSize(22); doc.setFont("helvetica","bold");
  doc.text("GFALens", M, 20);
  doc.setFontSize(9); doc.setFont("helvetica","normal"); doc.setTextColor(147,197,253);
  doc.text("Plateforme de gestion et supervision bancaire", M, 27);
  doc.setFillColor(239,68,68); doc.roundedRect(W-M-32,10,32,9,2,2,"F");
  doc.setTextColor(255,255,255); doc.setFontSize(7); doc.setFont("helvetica","bold");
  doc.text(t.pdfConf, W-M-16, 16, {align:"center"});
  doc.setFontSize(13); doc.text(rapport.titre, M, 39);

  let y = 58;
  doc.setFillColor(248,250,252); doc.setDrawColor(226,232,240);
  doc.roundedRect(M,y,CW,40,3,3,"FD");
  doc.setTextColor(30,58,138); doc.setFontSize(10); doc.setFont("helvetica","bold");
  doc.text(t.pdfSummary, M+5, y+8);
  doc.setDrawColor(59,130,246); doc.setLineWidth(0.5);
  doc.line(M+5,y+10,M+CW-5,y+10);
  const metrics = [
    {label:t.pdfFiliale, value:rapport.filiale},
    {label:t.pdfIncidents, value:String(rapport.incidents)},
    {label:t.pdfDispo, value:rapport.disponibilite},
    {label:t.pdfStatut, value:t.statuts?.[rapport.statut]||rapport.statut},
  ];
  metrics.forEach((m,i) => {
    const x = M+i*(CW/4)+CW/8;
    doc.setTextColor(100,116,139); doc.setFontSize(7); doc.setFont("helvetica","normal");
    doc.text(m.label, x, y+18, {align:"center"});
    doc.setTextColor(15,23,42); doc.setFontSize(9); doc.setFont("helvetica","bold");
    doc.text(m.value, x, y+26, {align:"center"});
  });
  y += 48;

  doc.setTextColor(30,58,138); doc.setFontSize(10); doc.setFont("helvetica","bold");
  doc.text(t.pdfDetails, M, y);
  doc.setDrawColor(59,130,246); doc.setLineWidth(0.4);
  doc.line(M, y+2, M+CW, y+2); y += 8;
  const rows = [
    ["Type", rapport.type], [t.pdfDate, rapport.dateGeneration],
    [t.pdfFiliale, rapport.filiale], [t.pdfAgence, rapport.agence],
    [t.pdfIncidents, String(rapport.incidents)], [t.pdfDispo, rapport.disponibilite],
    [t.pdfStatut, t.statuts?.[rapport.statut]||rapport.statut],
    [t.pdfSize, rapport.taille], [t.pdfGeneratedBy, rapport.generePar],
  ];
  rows.forEach(([label,value],i) => {
    const ry = y+i*9;
    if(i%2===0){doc.setFillColor(248,250,252); doc.rect(M,ry-4,CW,8,"F");}
    doc.setTextColor(100,116,139); doc.setFontSize(8); doc.setFont("helvetica","normal");
    doc.text(label, M+3, ry);
    doc.setTextColor(15,23,42); doc.setFont("helvetica","bold");
    doc.text(value||"—", M+70, ry);
  });

  const pH = 297;
  doc.setFillColor(30,58,138); doc.rect(0,pH-14,W,14,"F");
  doc.setTextColor(147,197,253); doc.setFontSize(7); doc.setFont("helvetica","normal");
  doc.text(t.pdfFooter, M, pH-6);
  doc.text(`${t.pdfDate} : ${new Date().toLocaleDateString()}`, W-M, pH-6, {align:"right"});
  doc.setTextColor(255,255,255); doc.text("1 / 1", W/2, pH-6, {align:"center"});
  doc.save(`${rapport.titre.replace(/\s+/g,"_")}.pdf`);
}

// ─── MINI CALENDRIER ──────────────────────────────────────────
function MiniCalendar({ value, onChange, label }) {
  const [currentMonth, setCurrentMonth] = useState(() => {
    if (value) return new Date(value + "-01");
    const d = new Date(); d.setDate(1); return d;
  });

  const [open, setOpen] = useState(false);

  const year  = currentMonth.getFullYear();
  const month = currentMonth.getMonth();

  const JOURS = ["Lu", "Ma", "Me", "Je", "Ve", "Sa", "Di"];
  const MOIS_FR = ["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"];

  const firstDay = new Date(year, month, 1).getDay();
  const offset   = firstDay === 0 ? 6 : firstDay - 1;
  const daysInMonth = new Date(year, month + 1, 0).getDate();

  const prevMonth = () => setCurrentMonth(new Date(year, month - 1, 1));
  const nextMonth = () => setCurrentMonth(new Date(year, month + 1, 1));

  const selectDay = (d) => {
    const dd = String(d).padStart(2, "0");
    const mm = String(month + 1).padStart(2, "0");
    onChange(`${year}-${mm}-${dd}`);
    setOpen(false);
  };

  const formatDisplay = (val) => {
    if (!val) return "";
    const [y, m, d] = val.split("-");
    return `${d}/${m}/${y}`;
  };

  const isSelected = (d) => {
    if (!value) return false;
    const [y, m, day] = value.split("-");
    return parseInt(y) === year && parseInt(m) === month + 1 && parseInt(day) === d;
  };

  const isToday = (d) => {
    const now = new Date();
    return now.getFullYear() === year && now.getMonth() === month && now.getDate() === d;
  };

  return (
    <div className="relative">
      <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{label}</label>
      <button
        type="button"
        onClick={() => setOpen(v => !v)}
        className="w-full flex items-center justify-between border border-gray-200 dark:border-gray-600 rounded-xl px-3 py-2.5 text-sm bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-100 hover:bg-white dark:hover:bg-gray-600 transition-colors"
      >
        <span className={value ? "text-gray-900 dark:text-gray-100" : "text-gray-400 dark:text-gray-500"}>
          {value ? formatDisplay(value) : "jj/mm/aaaa"}
        </span>
        <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
      </button>

      {open && (
        <div className="absolute z-50 mt-1 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 rounded-2xl shadow-xl p-4 w-72">
          {/* Navigation mois */}
          <div className="flex items-center justify-between mb-3">
            <button type="button" onClick={prevMonth}
              className="p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors text-gray-500 dark:text-gray-400">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
            </button>
            <span className="text-sm font-semibold text-gray-800 dark:text-gray-100">
              {MOIS_FR[month]} {year}
            </span>
            <button type="button" onClick={nextMonth}
              className="p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors text-gray-500 dark:text-gray-400">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
            </button>
          </div>

          {/* Jours de la semaine */}
          <div className="grid grid-cols-7 mb-1">
            {JOURS.map(j => (
              <div key={j} className="text-center text-xs font-semibold text-gray-400 dark:text-gray-500 py-1">{j}</div>
            ))}
          </div>

          {/* Cases du calendrier */}
          <div className="grid grid-cols-7 gap-0.5">
            {Array(offset).fill(null).map((_, i) => <div key={`e-${i}`} />)}
            {Array.from({ length: daysInMonth }, (_, i) => i + 1).map(d => (
              <button
                key={d}
                type="button"
                onClick={() => selectDay(d)}
                className={`h-8 w-8 mx-auto flex items-center justify-center rounded-full text-sm transition-colors ${
                  isSelected(d)
                    ? "bg-blue-700 text-white font-bold"
                    : isToday(d)
                    ? "border border-blue-400 text-blue-600 dark:text-blue-400 font-semibold"
                    : "text-gray-700 dark:text-gray-300 hover:bg-blue-50 dark:hover:bg-blue-900/30"
                }`}
              >
                {d}
              </button>
            ))}
          </div>

          {/* Bouton aujourd'hui */}
          <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-700 text-center">
            <button
              type="button"
              onClick={() => {
                const now = new Date();
                const dd = String(now.getDate()).padStart(2,"0");
                const mm = String(now.getMonth()+1).padStart(2,"0");
                onChange(`${now.getFullYear()}-${mm}-${dd}`);
                setOpen(false);
              }}
              className="text-xs text-blue-600 dark:text-blue-400 hover:underline"
            >
              Aujourd'hui
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── MODAL GÉNÉRER RAPPORT ─────────────────────────────────────
function ModalGenererRapport({ onClose, onGenerate, t }) {
  const [form, setForm] = useState({
    type: "", dateDebut: "", dateFin: "",
    filiale: "", agence: "", formats: ["PDF"],
  });
  const [loading, setLoading] = useState(false);
  const s = (k, v) => setForm(p => ({ ...p, [k]: v }));

  const toggleFormat = (f) => setForm(p => ({
    ...p,
    formats: p.formats.includes(f) ? p.formats.filter(x => x !== f) : [...p.formats, f],
  }));

  const allFiliales = [
    ...mockFiliales.map(f => ({ id: f.id, nom: f.nom })),
    ...mockFiliales.flatMap(f => (f.sousFiliales || []).map(sf => ({ id: sf.id, nom: `↳ ${sf.nom}` }))),
  ];

  const inp = "w-full border border-gray-200 dark:border-gray-600 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-100 transition-colors";
  const lbl = "block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1";

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.dateDebut || !form.dateFin) return;
    setLoading(true);
    await new Promise(r => setTimeout(r, 1500));
    setLoading(false);
    onGenerate(form);
    onClose();
  };

  const formatDate = (d) => {
    if (!d) return "";
    const [y, m, day] = d.split("-");
    return `${day}/${m}/${y}`;
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full max-w-lg transition-colors">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 dark:border-gray-700">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-blue-100 dark:bg-blue-900/40 rounded-xl flex items-center justify-center">
              <svg className="w-5 h-5 text-blue-700 dark:text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">{t.genTitle}</h3>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 text-2xl leading-none">×</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="px-6 py-5 space-y-4">

            {/* Type de rapport */}
            <div>
              <label className={lbl}>{t.genType}</label>
              <select required value={form.type} onChange={e => s("type", e.target.value)} className={inp}>
                <option value="">{t.genTypeDefault}</option>
                {t.TYPES_RAPPORT.map(tp => <option key={tp}>{tp}</option>)}
              </select>
            </div>

            {/* Période — 2 calendriers */}
            <div className="grid grid-cols-2 gap-3">
              <MiniCalendar
                value={form.dateDebut}
                onChange={v => s("dateDebut", v)}
                label={t.genPeriodeDebut}
              />
              <MiniCalendar
                value={form.dateFin}
                onChange={v => s("dateFin", v)}
                label={t.genPeriodeFin}
              />
            </div>

            {/* Résumé période sélectionnée */}
            {form.dateDebut && form.dateFin && (
              <div className="flex items-center gap-2 bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-800 rounded-xl px-3 py-2">
                <svg className="w-4 h-4 text-blue-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                <p className="text-xs text-blue-700 dark:text-blue-300">
                  {formatDate(form.dateDebut)} → {formatDate(form.dateFin)}
                </p>
              </div>
            )}

            {/* Filiale + Agence */}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className={lbl}>{t.genFiliale}</label>
                <select value={form.filiale} onChange={e => s("filiale", e.target.value)} className={inp}>
                  <option value="">{t.genFilialeDefault}</option>
                  {allFiliales.map(f => <option key={f.id} value={f.nom}>{f.nom}</option>)}
                </select>
              </div>
              <div>
                <label className={lbl}>{t.genAgence}</label>
                <input placeholder={t.genAgenceDefault} value={form.agence}
                  onChange={e => s("agence", e.target.value)} className={inp} />
              </div>
            </div>

            {/* Format */}
            <div>
              <label className={lbl}>{t.genFormat}</label>
              <div className="flex gap-4">
                {t.FORMATS.map(f => (
                  <label key={f} className="flex items-center gap-2 cursor-pointer">
                    <input type="checkbox" checked={form.formats.includes(f)}
                      onChange={() => toggleFormat(f)}
                      className="w-4 h-4 rounded border-gray-300 text-blue-700 accent-blue-700" />
                    <span className="text-sm text-gray-700 dark:text-gray-300">{f}</span>
                  </label>
                ))}
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="flex gap-3 px-6 pb-6">
            <button type="button" onClick={onClose}
              className="flex-1 py-2.5 border border-gray-200 dark:border-gray-600 rounded-xl text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors">
              {t.genCancel}
            </button>
            <button type="submit" disabled={loading || !form.dateDebut || !form.dateFin}
              className="flex-1 py-2.5 bg-blue-900 text-white rounded-xl text-sm font-medium hover:bg-blue-800 disabled:opacity-60 transition-colors flex items-center justify-center gap-2">
              {loading ? (
                <>
                  <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
                  </svg>
                  {t.genGenerating}
                </>
              ) : t.genSubmit}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// ─── PAGE PRINCIPALE ──────────────────────────────────────────
export default function RapportsPage() {
  const [typeFiltre, setTypeFiltre]     = useState("Tous");
  const [search, setSearch]             = useState("");
  const [detail, setDetail]             = useState(null);
  const [showGenModal, setShowGenModal] = useState(false);
  const [pdfLoading, setPdfLoading]     = useState(null);
  const [rapports, setRapports]         = useState(
    // Filtrer Audit des données initiales
    mockRapports.filter(r => r.type !== "Audit")
  );
  const { langue } = useAppSettings();
  const t = T[langue] || T.fr;

  const filtered = rapports.filter(r =>
    (typeFiltre === "Tous" || r.type === typeFiltre) &&
    r.titre.toLowerCase().includes(search.toLowerCase())
  );

  const handlePDF = async (rapport) => {
    setPdfLoading(rapport.id);
    try { await generatePDF(rapport, t); }
    catch { alert("Installez jsPDF : npm install jspdf"); }
    finally { setPdfLoading(null); }
  };

  const handleExport = (rapport, format) => {
    if (format === "PDF")   handlePDF(rapport);
    if (format === "Excel") exportExcel(rapport);
    if (format === "CSV")   exportCSV(rapport);
  };

  const handleGenerate = (form) => {
    const periode = form.dateDebut && form.dateFin
      ? `${form.dateDebut} → ${form.dateFin}`
      : "—";
    const newRapport = {
      id:              Date.now(),
      titre:           `Rapport ${form.type} — ${periode}`,
      type:            form.type,
      dateGeneration:  new Date().toISOString().slice(0, 10),
      filiale:         form.filiale || "Toutes",
      agence:          form.agence  || "Toutes",
      incidents:       0,
      disponibilite:   "—",
      statut:          "Généré",
      generePar:       "Leslie Jones",
      taille:          "1.2 MB",
      formats:         form.formats,
    };
    setRapports(prev => [newRapport, ...prev]);
  };

  return (
    <div className="flex-1 overflow-y-auto bg-gray-50 dark:bg-gray-900 transition-colors duration-300">

      {/* Header */}
      <div className="px-6 py-5 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 transition-colors">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-xl font-bold text-gray-900 dark:text-gray-100">{t.title}</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-0.5">{t.subtitle}</p>
          </div>
          <button onClick={() => setShowGenModal(true)}
            className="px-4 py-2.5 bg-blue-900 text-white text-sm font-medium rounded-xl hover:bg-blue-800 transition-colors flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
            </svg>
            {t.newBtn}
          </button>
        </div>
      </div>

      <div className="p-6 space-y-6">

        {/* KPIs */}
        <div className="grid grid-cols-3 gap-4">
          {[
            { label: t.kpi1, value: rapports.length,                                    color: "text-blue-900 dark:text-blue-400" },
            { label: t.kpi2, value: rapports.filter(r => r.statut === "Généré").length, color: "text-green-600 dark:text-green-400" },
            { label: t.kpi3, value: rapports.filter(r => r.statut !== "Généré").length, color: "text-yellow-600 dark:text-yellow-400" },
          ].map(({ label, value, color }) => (
            <div key={label} className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5 transition-colors">
              <p className="text-sm text-gray-500 dark:text-gray-400 mb-1">{label}</p>
              <p className={`text-2xl font-bold ${color}`}>{value}</p>
            </div>
          ))}
        </div>

        {/* Charts */}
        <div className="grid grid-cols-3 gap-4">
          <div className="col-span-2 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5 transition-colors">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-200 mb-3">{t.chartBar}</h3>
            <ResponsiveContainer width="100%" height={180}>
              <BarChart data={barData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#374151" />
                <XAxis dataKey="mois" tick={{ fontSize: 12, fill: "#9ca3af" }} />
                <YAxis tick={{ fontSize: 12, fill: "#9ca3af" }} />
                <Tooltip contentStyle={tooltipStyle} />
                <Legend wrapperStyle={{ fontSize: 12, color: "#9ca3af" }} />
                <Bar dataKey="mensuel"   name="Mensuel"   fill="#1e3a8a" radius={[4,4,0,0]} />
                <Bar dataKey="hebdo"     name="Hebdo"     fill="#60a5fa" radius={[4,4,0,0]} />
                <Bar dataKey="incidents" name="Incidents" fill="#ef4444" radius={[4,4,0,0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5 transition-colors">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-200 mb-3">{t.chartPie}</h3>
            <ResponsiveContainer width="100%" height={180}>
              <PieChart>
                <Pie data={pieData} cx="50%" cy="50%" outerRadius={65} dataKey="value">
                  {pieData.map((e, i) => <Cell key={i} fill={e.color} />)}
                </Pie>
                <Tooltip contentStyle={tooltipStyle} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5 transition-colors">
          <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-200 mb-3">{t.chartLine}</h3>
          <ResponsiveContainer width="100%" height={150}>
            <LineChart data={lineData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#374151" />
              <XAxis dataKey="mois" tick={{ fontSize: 12, fill: "#9ca3af" }} />
              <YAxis domain={[90, 100]} tick={{ fontSize: 12, fill: "#9ca3af" }} />
              <Tooltip contentStyle={tooltipStyle} />
              <Line type="monotone" dataKey="dispo" stroke="#3b82f6" strokeWidth={2} dot={{ r: 4 }} name="Disponibilité %" />
            </LineChart>
          </ResponsiveContainer>
        </div>

        {/* Tableau */}
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden transition-colors">
          <div className="px-6 py-4 border-b border-gray-100 dark:border-gray-700 flex items-center gap-3 flex-wrap">
            <input type="text" placeholder={t.searchPlaceholder} value={search}
              onChange={e => setSearch(e.target.value)}
              className="flex-1 max-w-sm px-4 py-2 text-sm border border-gray-200 dark:border-gray-600 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-100 transition-colors" />
            <div className="flex gap-2 flex-wrap">
              {TYPES_FILTRE.map(tp => (
                <button key={tp} onClick={() => setTypeFiltre(tp)}
                  className={`px-3 py-1.5 rounded-lg text-xs transition-colors ${typeFiltre === tp ? "bg-blue-900 text-white" : "bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600"}`}>
                  {tp}
                </button>
              ))}
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-gray-50 dark:bg-gray-700/50">
                <tr>
                  {t.tableCols.map(h => (
                    <th key={h} className="text-left py-3 px-4 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {filtered.map(r => (
                  <tr key={r.id} className="border-t border-gray-50 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/30 transition-colors">
                    <td className="py-3 px-4">
                      <p className="font-medium text-gray-900 dark:text-gray-100">{r.titre}</p>
                      <p className="text-xs text-gray-400 dark:text-gray-500">{t.par} {r.generePar}</p>
                    </td>
                    <td className="py-3 px-4">
                      <span className="px-2 py-0.5 bg-blue-100 dark:bg-blue-900/40 text-blue-800 dark:text-blue-300 text-xs rounded-full">{r.type}</span>
                    </td>
                    <td className="py-3 px-4 text-gray-500 dark:text-gray-400">{r.dateGeneration}</td>
                    <td className="py-3 px-4 text-gray-600 dark:text-gray-400">{r.filiale}</td>
                    <td className="py-3 px-4 text-gray-700 dark:text-gray-300 font-medium">{r.incidents}</td>
                    <td className="py-3 px-4 font-medium text-blue-900 dark:text-blue-400">{r.disponibilite}</td>
                    <td className="py-3 px-4">
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${STATUT_STYLES[r.statut] || "bg-gray-100 text-gray-700"}`}>
                        {t.statuts[r.statut] || r.statut}
                      </span>
                    </td>
                    <td className="py-3 px-4">
                      <div className="flex gap-1 flex-wrap items-center">
                        <button onClick={() => setDetail(r)}
                          className="text-xs text-blue-600 dark:text-blue-400 hover:underline px-1">{t.see}</button>
                        {r.statut === "Généré" && (
                          <>
                            <button onClick={() => handlePDF(r)} disabled={pdfLoading === r.id}
                              className="text-xs bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 hover:bg-red-100 px-2 py-0.5 rounded-lg transition-colors flex items-center gap-1">
                              {pdfLoading === r.id
                                ? <svg className="w-3 h-3 animate-spin" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/></svg>
                                : null}
                              PDF
                            </button>
                            {(r.formats || []).includes("Excel") && (
                              <button onClick={() => exportExcel(r)}
                                className="text-xs bg-green-50 dark:bg-green-900/20 text-green-600 dark:text-green-400 hover:bg-green-100 px-2 py-0.5 rounded-lg transition-colors">Excel</button>
                            )}
                            {(r.formats || []).includes("CSV") && (
                              <button onClick={() => exportCSV(r)}
                                className="text-xs bg-orange-50 dark:bg-orange-900/20 text-orange-600 dark:text-orange-400 hover:bg-orange-100 px-2 py-0.5 rounded-lg transition-colors">CSV</button>
                            )}
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Modal détail */}
      {detail && (
        <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full max-w-lg transition-colors">
            <div className="flex justify-between items-center px-6 py-4 border-b border-gray-100 dark:border-gray-700">
              <h3 className="font-semibold text-gray-900 dark:text-gray-100">{detail.titre}</h3>
              <button onClick={() => setDetail(null)} className="text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 text-xl">×</button>
            </div>
            <div className="p-6 space-y-3">
              {[
                [t.modalType, detail.type], [t.modalDate, detail.dateGeneration],
                [t.modalFiliale, detail.filiale], [t.modalAgence, detail.agence],
                [t.modalIncidents, detail.incidents], [t.modalDispo, detail.disponibilite],
                [t.modalStatut, t.statuts[detail.statut] || detail.statut],
                [t.modalTaille, detail.taille],
              ].map(([k, v]) => (
                <div key={k} className="flex justify-between text-sm">
                  <span className="text-gray-500 dark:text-gray-400">{k}</span>
                  <span className="font-medium text-gray-900 dark:text-gray-100">{v}</span>
                </div>
              ))}
            </div>
            <div className="flex gap-3 px-6 pb-6">
              {(detail.formats || ["PDF"]).map(f => (
                <button key={f} onClick={() => handleExport(detail, f)}
                  className="flex-1 py-2 border border-blue-200 dark:border-blue-700 text-blue-700 dark:text-blue-400 rounded-xl text-sm hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors flex items-center justify-center gap-1">
                  {pdfLoading === detail.id && f === "PDF"
                    ? <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/></svg>
                    : null}
                  {t.export} {f}
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Modal générer */}
      {showGenModal && (
        <ModalGenererRapport
          onClose={() => setShowGenModal(false)}
          onGenerate={handleGenerate}
          t={t}
        />
      )}
    </div>
  );
}
